<?php
//echo $behavid;
if ($projectid == 0 && $componentid == 0 && $subcomponentid == 0 && $activityid == 0) {
    if ($behavid == 0 || $behavid == 1) {
        $dcode = $componentid;
        $tcode = $subcomponentid;
        $vcode = $activityid;
        $behavid = $behavid;
        //echo $query="SELECT * FROM p2003village where dcode=$dcode";
        $query = "SELECT a.giscode as giscode, b.village as village, b.x as x, b.y as y, b.dcode as dcode, b.tcode as tcode, b.code as code FROM p2004vp a inner join p2003village b on (a.giscode=b.giscode)";
        $res1 = mysql_query($query);

        // STEP 3: Store the marker info in arrays for each row found
        // save the count of markers for later

        $mrk_cnt = 0;
        while ($obj1 = mysql_fetch_array($res1)) {

            $lat[$mrk_cnt] = $obj1['y'];
            $lng[$mrk_cnt] = $obj1['x'];
            $inf[$mrk_cnt] = $obj1['village'];

            $dc[$mrk_cnt] = $obj1['dcode'];
            $tc[$mrk_cnt] = $obj1['tcode'];
            $co[$mrk_cnt] = $obj1['code'];
            $mrk_cnt++;
        }
?>

        <script type='text/javascript'>
            var point;
            var mrktx;

            function initMap2() {

                addTo = 0;
                var latlng = new google.maps.LatLng('<?php echo $lat['0']  ?>', '<?php echo $lng['0']  ?>');

                var myOptions = {

                    center: latlng,
                    mapTypeId: google.maps.MapTypeId.SATELLITE,
                    mapTypeControl: true,
                };
                // NOTE: all values: latitude, longitude, zoom, etc.
                //       should also come from the database for flexibility
                var icon = new google.maps.MarkerImage("<?php echo $_CONFIG["site_url"] ?>" + "images/blue1.png");
                var map = new google.maps.Map(document.getElementById("map"),
                    myOptions);
                // This next block of JavaScript needs to be generated by PHP 
                // to 'add-in' the information from the arrays

                map.setZoom(9);
                <?php

                for ($lcnt = 0; $lcnt < $mrk_cnt; $lcnt++) {

                    echo "var point$lcnt = new google.maps.LatLng($lat[$lcnt], $lng[$lcnt]);\n";
                    echo "var mrktx$lcnt = \"$inf[$lcnt]\";\n";
                    echo "var infowindow$lcnt = new google.maps.InfoWindow({
                    content: mrktx$lcnt
                    });";
                    echo "var marker$lcnt = new google.maps.Marker({position: point$lcnt,icon: icon, map: map});\n";
                    echo "google.maps.event.addListener(marker$lcnt, 
                    'click', function() {
                        infowindow$lcnt.open(map,marker$lcnt);
                        window.location.href = '$_CONFIG[site_url]qrdash-home.php?map_id=3&componentid=$dc[$lcnt]&subcomponentid=$tc[$lcnt]&activityid=$co[$lcnt]';
                        
                        });\n";
                }
                ?>
            }
            //window.onload = initMap2;
            google.maps.event.addDomListener(window, 'load', initMap2);
        </script>

        <?php
        if ($_GET['map_id'] == 1) {
        ?>
            <script type='text/javascript'>
                var point;
                var mrktx;

                function initMap2() {

                    addTo = 0;
                    var latlng = new google.maps.LatLng('<?php echo $lat['0']  ?>', '<?php echo $lng['0']  ?>');
                    var myOptions = {
                        zoom: 9,
                        center: latlng,
                        mapTypeId: google.maps.MapTypeId.ROADMAP,
                        mapTypeControl: false,
                    };
                    // NOTE: all values: latitude, longitude, zoom, etc.
                    //       should also come from the database for flexibility
                    var icon = new google.maps.MarkerImage("<?php echo $_CONFIG["site_url"] ?>" + "images/blue1.png");
                    var map = new google.maps.Map(document.getElementById("map"),
                        myOptions);
                    // This next block of JavaScript needs to be generated by PHP 
                    // to 'add-in' the information from the arrays

                    <?php

                    for ($lcnt = 0; $lcnt < $mrk_cnt; $lcnt++) {

                        echo "var point$lcnt = new google.maps.LatLng($lat[$lcnt], $lng[$lcnt]);\n";
                        echo "var mrktx$lcnt = \"$inf[$lcnt]\";\n";
                        echo "var infowindow$lcnt = new google.maps.InfoWindow({
   			content: mrktx$lcnt
			});";
                        echo "var marker$lcnt = new google.maps.Marker({position: point$lcnt,icon: icon, map: map});\n";
                        echo "google.maps.event.addListener(marker$lcnt, 
         'click', function() {
   		     infowindow$lcnt.open(map,marker$lcnt);
			  window.location.href = '$_CONFIG[site_url]qrdash-home.php?map_id=1&componentid=$dc[$lcnt]&subcomponentid=$tc[$lcnt]&activityid=$co[$lcnt]';
          });\n";
                    }

                    ?>

                }
                google.maps.event.addDomListener(window, 'load', initMap2);
                //window.onload = initMap2;
            </script>
        <?php
        }
        if ($_GET['map_id'] == 2) {
        ?>
            <script type='text/javascript'>
                var point;
                var mrktx;

                function initMap2() {

                    addTo = 0;
                    var latlng = new google.maps.LatLng('<?php echo $lat['0']  ?>', '<?php echo $lng['0']  ?>');
                    var myOptions = {
                        zoom: 9,
                        center: latlng,
                        mapTypeId: google.maps.MapTypeId.HYBRID,
                        mapTypeControl: false,
                    };
                    // NOTE: all values: latitude, longitude, zoom, etc.
                    //       should also come from the database for flexibility
                    var icon = new google.maps.MarkerImage("<?php echo $_CONFIG["site_url"] ?>" + "images/blue1.png");
                    var map = new google.maps.Map(document.getElementById("map"),
                        myOptions);
                    // This next block of JavaScript needs to be generated by PHP 
                    // to 'add-in' the information from the arrays

                    <?php

                    for ($lcnt = 0; $lcnt < $mrk_cnt; $lcnt++) {

                        echo "var point$lcnt = new google.maps.LatLng($lat[$lcnt], $lng[$lcnt]);\n";
                        echo "var mrktx$lcnt = \"$inf[$lcnt]\";\n";
                        echo "var infowindow$lcnt = new google.maps.InfoWindow({
   			content: mrktx$lcnt
			});";
                        echo "var marker$lcnt = new google.maps.Marker({position: point$lcnt,icon: icon, map: map});\n";
                        echo "google.maps.event.addListener(marker$lcnt, 
         'click', function() {
   		     infowindow$lcnt.open(map,marker$lcnt);
			  window.location.href = '$_CONFIG[site_url]qrdash-home.php?map_id=2&componentid=$dc[$lcnt]&subcomponentid=$tc[$lcnt]&activityid=$co[$lcnt]';
          });\n";
                    }

                    ?>

                }
                //window.onload = initMap2;
                google.maps.event.addDomListener(window, 'load', initMap2);
            </script>
        <?php
        }
        if ($_GET['map_id'] == 3) {
        ?>
            <script type='text/javascript'>
                var point;
                var mrktx;

                function initMap2() {

                    addTo = 0;
                    var latlng = new google.maps.LatLng('<?php echo $lat['0']  ?>', '<?php echo $lng['0']  ?>');
                    var myOptions = {
                        zoom: 9,
                        center: latlng,
                        mapTypeId: google.maps.MapTypeId.SATELLITE,
                        mapTypeControl: false,
                    };
                    // NOTE: all values: latitude, longitude, zoom, etc.
                    //       should also come from the database for flexibility
                    var icon = new google.maps.MarkerImage("<?php echo $_CONFIG["site_url"] ?>" + "images/blue1.png");
                    var map = new google.maps.Map(document.getElementById("map"),
                        myOptions);
                    // This next block of JavaScript needs to be generated by PHP 
                    // to 'add-in' the information from the arrays

                    <?php

                    for ($lcnt = 0; $lcnt < $mrk_cnt; $lcnt++) {

                        echo "var point$lcnt = new google.maps.LatLng($lat[$lcnt], $lng[$lcnt]);\n";
                        echo "var mrktx$lcnt = \"$inf[$lcnt]\";\n";
                        echo "var infowindow$lcnt = new google.maps.InfoWindow({
   			content: mrktx$lcnt
			});";
                        echo "var marker$lcnt = new google.maps.Marker({position: point$lcnt,icon: icon, map: map});\n";
                        echo "google.maps.event.addListener(marker$lcnt, 
         'click', function() {
   		     infowindow$lcnt.open(map,marker$lcnt);
			  window.location.href = '$_CONFIG[site_url]qrdash-home.php?map_id=3&componentid=$dc[$lcnt]&subcomponentid=$tc[$lcnt]&activityid=$co[$lcnt]';
          });\n";
                    }

                    ?>

                }
                //window.onload = initMap2;
                google.maps.event.addDomListener(window, 'load', initMap2);
            </script>
        <?php
        }
        if ($_GET['map_id'] == 4) {
        ?>
            <script type='text/javascript'>
                var point;
                var mrktx;

                function initMap2() {

                    addTo = 0;
                    var latlng = new google.maps.LatLng('<?php echo $lat['0']  ?>', '<?php echo $lng['0']  ?>');
                    var myOptions = {
                        zoom: 9,
                        center: latlng,
                        mapTypeId: google.maps.MapTypeId.TERRAIN,
                        mapTypeControl: false,
                    };
                    // NOTE: all values: latitude, longitude, zoom, etc.
                    //       should also come from the database for flexibility
                    var icon = new google.maps.MarkerImage("<?php echo $_CONFIG["site_url"] ?>" + "images/blue1.png");
                    var map = new google.maps.Map(document.getElementById("map"),
                        myOptions);
                    // This next block of JavaScript needs to be generated by PHP 
                    // to 'add-in' the information from the arrays

                    <?php

                    for ($lcnt = 0; $lcnt < $mrk_cnt; $lcnt++) {

                        echo "var point$lcnt = new google.maps.LatLng($lat[$lcnt], $lng[$lcnt]);\n";
                        echo "var mrktx$lcnt = \"$inf[$lcnt]\";\n";
                        echo "var infowindow$lcnt = new google.maps.InfoWindow({
   			content: mrktx$lcnt
			});";
                        echo "var marker$lcnt = new google.maps.Marker({position: point$lcnt,icon: icon, map: map});\n";
                        echo "google.maps.event.addListener(marker$lcnt, 
         'click', function() {
   		     infowindow$lcnt.open(map,marker$lcnt);
			  window.location.href = '$_CONFIG[site_url]qrdash-home.php?map_id=4&componentid=$dc[$lcnt]&subcomponentid=$tc[$lcnt]&activityid=$co[$lcnt]';
          });\n";
                    }

                    ?>

                }
                //window.onload = initMap2;
                google.maps.event.addDomListener(window, 'load', initMap2);
            </script>
        <?php
        }
        ?>


        <section class="mb-4">
            <div class="container-fluid" style="padding-top: 0px !important;">
                <div class="card">
                    <div class="card-body">
                        <div class="d-flex">
                            <p class="d-flex flex-row">
                                <!-- <span class="text-bold text-lg"><?php echo "Zone Visits";  ?> &raquo;<?= $dates; ?></span> -->
                            </p>
                        </div>
                        <div id="map"></div>
                    </div>
                </div>

                <div class="card">
                    <div class="card-body">
                        <div class="btn-group btn-group-sm" role="group" id="tabs_ns">
                            <a class="btn btn-secondary" href="#demo">Demographic</a>
                            <a class="btn btn-secondary" href="#edu">Education</a>
                            <a class="btn btn-secondary" href="#wforce">Work Force</a>
                          
                            <!-- <a class="btn btn-secondary" href="#sdw">Drinking Water</a>
                            <a class="btn btn-secondary" href="#ensureimprovws1">Improved WScheme</a>
                            <a class="btn btn-secondary" href="#srcnondrink1">Source Non DWater</a>
                            <a class="btn btn-secondary" href="#hhawareyes1">Awareness</a> -->
                        </div>
                    </div>
                </div>

                <div class="tabContent" id="demo">
                        <?php

                        $iCount = 0;
						
						$SQL = "Select sum(tot_m) as admales, sum(tot_f) as adfemales, sum(m_06) as chmales, sum(f_06) as chfemales from p2004vp";
						
						
                      /*  $SQL = "Select sum(epadmale) as admales, sum(epadfemale) as adfemales, sum(epchmale) as chmales, sum(epchfemale) as chfemales from p2004vp where dcode=$dcode and tcode=$tcode and vcode=$vcode";*/
                        $reportresult = mysql_query($SQL);
                        $iCount = mysql_num_rows($reportresult);
                        if ($iCount > 0) {
                            while ($reportdata = mysql_fetch_array($reportresult)) {
                                $adultmales        = $reportdata['admales'];
                                $adultfemales    = $reportdata['adfemales'];
                                $childmales        = $reportdata['chmales'];
                                $childfemales    = $reportdata['chfemales'];

                                $adultmales1 = number_format(($adultmales / ($adultmales + $adultfemales) * 100), 2);
                                $adultfemales1 = number_format(($adultfemales / ($adultmales + $adultfemales) * 100), 2);

                                $childmales1 = number_format(($childmales / ($childmales + $childfemales) * 100), 2);
                                $childfemales1 = number_format(($childfemales / ($childmales + $childfemales) * 100), 2);
                            }
                        }
                        ?>
                        <div class="card-deck">
                            <div class="card">
                                <div class="card-header border-0">
                                    <h3 class="card-title"><i class="fas fa-chart-pie mr-1"></i> Data on Bar Chart</h3>
                                </div>
                                <div class="card-body">
                                    <div class="d-flex">
                                        <figure class="highcharts-figure">
                                            <div id="Demographic"></div>
                                        </figure>
                                    </div>
                                </div>
                            </div>
                            <div class="card">
                                <div class="card-header">
                                    <h3 class="card-title"><i class="fas fa-scroll mr-1"></i>Demographic Information</h3>
                                </div>
                                <div class="card-body">
                                    <table id="example1" class="table table-bordered table-striped">
                                        <thead>
                                            <tr>
                                                <th>Description</th>
                                                <th>Male</th>
                                                <th>Female</th>
                                                <th>Total</th>
                                                <th>% of Male</th>
                                                <th>% of Female</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>Adult</td>
                                                <td><?= number_format($adultmales, 0); ?></td>
                                                <td><?= number_format($adultfemales, 0); ?></td>
                                                <td><?= number_format(($adultmales + $adultfemales), 0); ?></td>
                                                <td><?= ($adultmales + $adultfemales) > 0 ? number_format(($adultmales / ($adultmales + $adultfemales) * 100), 2) : "0.00"; ?></td>
                                                <td><?= ($adultmales + $adultfemales) > 0 ? number_format(($adultfemales / ($adultmales + $adultfemales) * 100), 2) : "0,00"; ?></td>
                                            </tr>
                                            <tr>
                                                <td>Children up to 6 years</td>
                                                <td><?= number_format($childmales, 0); ?></td>
                                                <td><?= number_format($childfemales, 0); ?></td>
                                                <td><?= number_format(($childmales + $childfemales), 0); ?></td>
                                                <td><?= ($childmales + $childfemales) > 0 ? number_format(($childmales / ($childmales + $childfemales) * 100), 2) : "0.00"; ?></td>
                                                <td><?= ($childmales + $childfemales) > 0 ? number_format(($childfemales / ($childmales + $childfemales) * 100), 2) : "0.00"; ?></td>
                                            </tr>
                                            <tr>
                                                <td>Total</td>
                                                <td><?= number_format(($adultmales + $childmales), 0); ?></td>
                                                <td><?= number_format(($adultfemales + $childfemales), 0); ?></td>
                                                <td><?= number_format(($adultmales + $adultfemales + $childmales + $childfemales), 0); ?></td>
                                                <td><?= ($adultmales + $adultfemales + $childmales + $childfemales) > 0 ? number_format((($adultmales + $childmales) / ($adultmales + $adultfemales + $childmales + $childfemales) * 100), 2) : "0.00"; ?></td>
                                                <td><?= ($adultmales + $adultfemales + $childmales + $childfemales) > 0 ? number_format((($adultfemales + $childfemales) / ($adultmales + $adultfemales + $childmales + $childfemales) * 100), 2) : "0.00"; ?></td>
                                            </tr>
                                        </tbody>
                                        <tfoot>
                                            <tr>
                                                <th>Description</th>
                                                <th>Male</th>
                                                <th>Female</th>
                                                <th>Total</th>
                                                <th>% of Male</th>
                                                <th>% of Female</th>
                                            </tr>
                                        </tfoot>
                                    </table>
                                </div>
                            </div>
                            <script type="text/javascript">
                                $(function() {
                                    $('#Demographic').highcharts({
                                        chart: {
                                            type: 'column'
                                        },
                                        title: {
                                            text: 'Demographic Mix'
                                        },
                                        xAxis: {
                                            categories: ['Male', 'Female']
                                        },
                                        yAxis: {
                                            min: 0,
                                            title: {
                                                text: 'Percentage (%)'
                                            }
                                        },
                                        credits: {
                                            enabled: false
                                        },
                                        tooltip: {
                                            pointFormat: '{series.name}: <b>{point.y:.1f}%</b>',
                                        },
                                        series: [{
                                            name: 'Adult',
                                            data: [<?php echo $adultmales1; ?>, <?php echo $adultfemales1; ?>]
                                        }, {
                                            name: 'Children up to 6 years',
                                            data: [<?php echo $childmales1; ?>, <?php echo $childfemales1; ?>]
                                        }]
                                    });
                                });
                            </script>
                        </div>
                    </div>
                <div class="tabContent" id="edu">
                        <?php

                        $iCount = 0;
						
						$SQL = "Select sum(m_lit) as litmales, sum(f_lit) as litfemales, sum(m_ill) as illmales, sum(f_ill) as illfemales from p2004vp";
						
						
                      /*  $SQL = "Select sum(epadmale) as admales, sum(epadfemale) as adfemales, sum(epchmale) as chmales, sum(epchfemale) as chfemales from p2004vp where dcode=$dcode and tcode=$tcode and vcode=$vcode";*/
                        $reportresult = mysql_query($SQL);
                        $iCount = mysql_num_rows($reportresult);
                        if ($iCount > 0) {
                            while ($reportdata = mysql_fetch_array($reportresult)) {
                                $litmales        = $reportdata['litmales'];
                                $litfemales    = $reportdata['litfemales'];
                                $illmales        = $reportdata['illmales'];
                                $illfemales    = $reportdata['illfemales'];

                                $litmales1 = number_format(($litmales / ($litmales + $litfemales) * 100), 2);
                                $litfemales1 = number_format(($litfemales / ($litmales + $litfemales) * 100), 2);

                                $illmales1 = number_format(($illmales / ($illmales + $illfemales) * 100), 2);
                                $illfemales1 = number_format(($illfemales / ($illmales + $illfemales) * 100), 2);
                            }
                        }
                        ?>
                        <div class="card-deck">
                            <div class="card">
                                <div class="card-header border-0">
                                    <h3 class="card-title"><i class="fas fa-chart-pie mr-1"></i> Data on Bar Chart</h3>
                                </div>
                                <div class="card-body">
                                    <div class="d-flex">
                                        <figure class="highcharts-figure">
                                            <div id="Education"></div>
                                        </figure>
                                    </div>
                                </div>
                            </div>
                            <div class="card">
                                <div class="card-header">
                                    <h3 class="card-title"><i class="fas fa-scroll mr-1"></i>Literacy Information</h3>
                                </div>
                                <div class="card-body">
                                    <table id="example1" class="table table-bordered table-striped">
                                        <thead>
                                            <tr>
                                                <th>Description</th>
                                                <th>Male</th>
                                                <th>Female</th>
                                                <th>Total</th>
                                                <th>% of Male</th>
                                                <th>% of Female</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>Literacy</td>
                                                <td><?= number_format($litmales, 0); ?></td>
                                                <td><?= number_format($litfemales, 0); ?></td>
                                                <td><?= number_format(($litmales + $litfemales), 0); ?></td>
                                                <td><?= ($litmales + $litfemales) > 0 ? number_format(($litmales / ($litmales + $litfemales) * 100), 2) : "0.00"; ?></td>
                                                <td><?= ($litmales + $litfemales) > 0 ? number_format(($litfemales / ($litmales + $litfemales) * 100), 2) : "0,00"; ?></td>
                                            </tr>
                                            <tr>
                                                <td>Illiteracy</td>
                                                <td><?= number_format($illmales, 0); ?></td>
                                                <td><?= number_format($illfemales, 0); ?></td>
                                                <td><?= number_format(($illmales + $illfemales), 0); ?></td>
                                                <td><?= ($illdmales + $illfemales) > 0 ? number_format(($illmales / ($illmales + $illfemales) * 100), 2) : "0.00"; ?></td>
                                                <td><?= ($illmales + $illfemales) > 0 ? number_format(($illfemales / ($illmales + $illfemales) * 100), 2) : "0.00"; ?></td>
                                            </tr>
                                            <tr>
                                                <td>Total</td>
                                                <td><?= number_format(($litmales + $illmales), 0); ?></td>
                                                <td><?= number_format(($litfemales + $illfemales), 0); ?></td>
                                                <td><?= number_format(($litmales + $litfemales + $illmales + $illfemales), 0); ?></td>
                                                <td><?= ($litmales + $litfemales + $illmales + $illfemales) > 0 ? number_format((($litmales + $illmales) / ($litmales + $litfemales + $illmales + $illfemales) * 100), 2) : "0.00"; ?></td>
                                                <td><?= ($litmales + $litfemales + $illmales + $illfemales) > 0 ? number_format((($litfemales + $illfemales) / ($litmales + $litfemales + $illmales + $illfemales) * 100), 2) : "0.00"; ?></td>
                                            </tr>
                                        </tbody>
                                        <tfoot>
                                            <tr>
                                                <th>Description</th>
                                                <th>Male</th>
                                                <th>Female</th>
                                                <th>Total</th>
                                                <th>% of Male</th>
                                                <th>% of Female</th>
                                            </tr>
                                        </tfoot>
                                    </table>
                                </div>
                            </div>
                            <script type="text/javascript">
                                $(function() {
                                    $('#Education').highcharts({
                                        chart: {
                                            type: 'column'
                                        },
                                        title: {
                                            text: 'Literacy Information'
                                        },
                                        xAxis: {
                                            categories: ['Male', 'Female']
                                        },
                                        yAxis: {
                                            min: 0,
                                            title: {
                                                text: 'Percentage (%)'
                                            }
                                        },
                                        credits: {
                                            enabled: false
                                        },
                                        tooltip: {
                                            pointFormat: '{series.name}: <b>{point.y:.1f}%</b>',
                                        },
                                        series: [{
                                            name: 'Literacy',
                                            data: [<?php echo $litmales1; ?>, <?php echo $litfemales1; ?>]
                                        }, {
                                            name: 'Illiteracy',
                                            data: [<?php echo $illmales1; ?>, <?php echo $illfemales1; ?>]
                                        }]
                                    });
                                });
                            </script>
                        </div>
                    </div>
                <div class="tabContent" id="wforce">
                        <?php

                        $iCount = 0;
						
						$SQL = "Select sum(mainwork_m) as mainwork_m, sum(mainwork_f) as mainwork_f, sum(main_cl_m) as main_cl_m, sum(main_cl_f) as main_cl_f,sum(main_al_m) as main_al_m, sum(main_al_f) as main_al_f, sum(main_hh_m) as main_hh_m, sum(main_hh_f) as main_hh_f, sum(main_ot_m) as main_ot_m, sum(main_ot_f) as main_ot_f, sum(margwork_m) as margwork_m, sum(margwork_f) as margwork_f from p2004vp";
						
						
                      /*  $SQL = "Select sum(epadmale) as admales, sum(epadfemale) as adfemales, sum(epchmale) as chmales, sum(epchfemale) as chfemales from p2004vp where dcode=$dcode and tcode=$tcode and vcode=$vcode";*/
                        $reportresult = mysql_query($SQL);
                        $iCount = mysql_num_rows($reportresult);
                        if ($iCount > 0) {
                            while ($reportdata = mysql_fetch_array($reportresult)) {
                                $mwmales        = $reportdata['mainwork_m'];
                                $mwfemales    = $reportdata['mainwork_f'];
                                $mcmales        = $reportdata['main_cl_m'];
                                $mcfemales    = $reportdata['main_cl_f'];
								
								
								$mamales        = $reportdata['main_al_m'];
                                $mafemales    = $reportdata['main_al_f'];
                                $mhmales        = $reportdata['main_hh_m'];
                                $mhfemales    = $reportdata['main_hh_f'];
								
								$momales        = $reportdata['main_ot_m'];
                                $mofemales    = $reportdata['main_ot_f'];
                                $mgmales        = $reportdata['margwork_m'];
                                $mgfemales    = $reportdata['margwork_f'];

                                $mwmales1 = number_format(($mwmales / ($mwmales + $mwfemales) * 100), 2);
                                $mwfemales1 = number_format(($mwfemales / ($mwmales + $mwfemales) * 100), 2);

                                $mcmales1 = number_format(($mcmales / ($mcmales + $mcfemales) * 100), 2);
                                $mcfemales1 = number_format(($mcfemales / ($mcmales + $mcfemales) * 100), 2);
								
								//al
								 $mamales1 = number_format(($mamales / ($mamales + $mafemales) * 100), 2);
                                $mafemales1 = number_format(($mafemales / ($mamales + $mafemales) * 100), 2);
								//hh
                                $mhmales1 = number_format(($mhmales / ($mhmales + $mhfemales) * 100), 2);
                                $mhfemales1 = number_format(($mhfemales / ($mhmales + $mhfemales) * 100), 2);
								//ot
								$momales1 = number_format(($momales / ($momales + $mofemales) * 100), 2);
                                $mofemales1 = number_format(($mofemales / ($momales + $mofemales) * 100), 2);
								
								//margwork
								$mgmales1 = number_format(($mgmales / ($mgmales + $mgfemales) * 100), 2);
                                $mgfemales1 = number_format(($mgfemales / ($mgmales + $mgfemales) * 100), 2);
								
								
                            }
                        }
                        ?>
                        <div class="card-deck">
                            <div class="card">
                                <div class="card-header border-0">
                                    <h3 class="card-title"><i class="fas fa-chart-pie mr-1"></i> Data on Bar Chart</h3>
                                </div>
                                <div class="card-body">
                                    <div class="d-flex">
                                        <figure class="highcharts-figure">
                                            <div id="Workforce"></div>
                                        </figure>
                                    </div>
                                </div>
                            </div>
                            <div class="card">
                                <div class="card-header">
                                    <h3 class="card-title"><i class="fas fa-scroll mr-1"></i>Workforce Information</h3>
                                </div>
                                <div class="card-body">
                                    <table id="example1" class="table table-bordered table-striped">
                                        <thead>
                                            <tr>
                                                <th>Description</th>
                                                <th>MainWork</th>
                                                <th>MainCL</th>
                                                <th>MainAL</th>
                                                <th>MainHH</th>
                                                <th>MainOT</th>
                                                <th>MargWork</th>
                                                
                                                <!--<th>% of Male</th>
                                                <th>% of Female</th>-->
                                                
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>% of Male</td>
                                                 <td><?= ($mwmales + $mwfemales) > 0 ? number_format(($mwmales / ($mwmales + $mwfemales) * 100), 2) : "0.00"; ?></td>
                                                <td><?= ($mcmales + $mcfemales) > 0 ? number_format(($mcmales / ($mcmales + $mcfemales) * 100), 2) : "0,00"; ?></td>
                                                <td><?= ($mamales + $mafemales) > 0 ? number_format(($mamales / ($mamales + $mafemales) * 100), 2) : "0.00"; ?></td>
                                                <td><?= ($mhmales + $mhfemales) > 0 ? number_format(($mhmales / ($mhmales + $mhfemales) * 100), 2) : "0,00"; ?></td>
                                                <td><?= ($momales + $mofemales) > 0 ? number_format(($momales / ($momales + $mofemales) * 100), 2) : "0.00"; ?></td>
                                                <td><?= ($mgmales + $mgfemales) > 0 ? number_format(($mgmales / ($mgmales + $mgfemales) * 100), 2) : "0,00"; ?></td>
                                                 
                                                 
                                                
                                                                                             
                                            </tr>
                                            <tr>
                                                <td>% of Female</td>
                                               
                                                <td><?= ($mwmales + $mwfemales) > 0 ? number_format(($mwfemales / ($mwmales + $mwfemales) * 100), 2) : "0.00"; ?></td>
                                                <td><?= ($mcmales + $mcfemales) > 0 ? number_format(($mcfemales / ($mcmales + $mcfemales) * 100), 2) : "0,00"; ?></td>
                                                <td><?= ($mamales + $mafemales) > 0 ? number_format(($mafemales / ($mamales + $mafemales) * 100), 2) : "0.00"; ?></td>
                                                <td><?= ($mhmales + $mhfemales) > 0 ? number_format(($mhfemales / ($mhmales + $mhfemales) * 100), 2) : "0,00"; ?></td>
                                                <td><?= ($momales + $mofemales) > 0 ? number_format(($mofemales / ($momales + $mofemales) * 100), 2) : "0.00"; ?></td>
                                                <td><?= ($mgmales + $mgfemales) > 0 ? number_format(($mgfemales / ($mgmales + $mgfemales) * 100), 2) : "0,00"; ?></td>
                                               
                                                
                                            </tr>
                                            
                                        </tbody>
                                        <tfoot>
                                            <tr>
                                                <th>Description</th>
                                                <th>MainWork</th>
                                                <th>MainCL</th>
                                               <th>MainAL</th>
                                                <th>MainHH</th>
                                                <th>MainOT</th>
                                                <th>MargWork</th>
                                              
                                            </tr>
                                        </tfoot>
                                    </table>
                                </div>
                            </div>
                            <script type="text/javascript">
                                $(function() {
                                    $('#Workforce').highcharts({
                                        chart: {
                                            type: 'column'
                                        },
                                        title: {
                                            text: 'Work Force'
                                        },
                                        xAxis: {
                                            categories: ['MainWork', 'Cultivators','Agricultural Laborers', 'Household Industry','Others', 'MargWork']
                                        },
                                        yAxis: {
                                            min: 0,
                                            title: {
                                                text: 'Percentage (%)'
                                            }
                                        },
                                        credits: {
                                            enabled: false
                                        },
                                        tooltip: {
                                            pointFormat: '{series.name}: <b>{point.y:.1f}%</b>',
                                        },
                                        series: [{
                                            name: 'Male',
                                            data: [<?php echo $mwmales1; ?>, <?php echo $mcmales1; ?>,<?php echo $mamales1; ?>, <?php echo $mhmales1; ?>,<?php echo $momales1; ?>, <?php echo $mgmales1; ?>]
                                        }, {
                                            name: 'Female',
                                            data: [<?php echo $mwfemales1; ?>, <?php echo $mcfemales1; ?>,<?php echo $mafemales1; ?>, <?php echo $mhfemales1; ?>,<?php echo $mofemales1; ?>, <?php echo $mgfemales1; ?>]
                                        }]
                                    });
                                });
                            </script>
                        </div>
                    </div>
                
            </div>
        </section>


<?php
    }
} ?>